name: Build Sandbox Docker Image

on:
  push:
    branches:
      - main
      - varnica-dev
    paths:
      - 'backend/sandbox/docker/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        shell: bash
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          fi
        id: get_tag

      - name: Build and push Sandbox image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/sandbox/docker
          file: ./backend/sandbox/docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}/sandbox:${{ steps.get_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
